### ISSUE TITLE
Strange underline of the rotated header in the active note

### ISSUE THREAD

**Issue by krnl0138** [deathau/sliding-panes-obsidian#108]
Version installed: version 3.0.0 (currently installed 3.2.5) 

I've experienced the bug with 3.0.0 version when the panes didn't stack up.
I uninstalled the plugin and re-installed it via obsidian browser.

Now I have an underlined header in the active note. This happens only when the option 'toggle rotated headers' is turned on.
I believe it wasn't like this before. Is it an intended behaviour now?

I include the screenshot of it: the blue line after the header. It goes all the way down of the pane.
<img width="475" alt="Screenshot 2022-07-05 at 08 35 55" src="https://user-images.githubusercontent.com/22024672/177250783-78347534-fb90-46c5-ae56-c44f389ce6a7.png">

**Comment by anvimea** [comment]
Encountering same issue, also seems to revolve around "toggle rotated headers".
![Obsidian_2i4HXzq8YE](https://user-images.githubusercontent.com/20266830/177306554-03bf4fe9-21e9-4d42-a2c6-8b64271933b0.png)

**Comment by krnl0138** [comment]
Looks like it was fixed. Closing.
