### ISSUE TITLE
Tabs (new core feature in Obsidian 0.16.0) break the plugin

### ISSUE THREAD

**Issue by approximate** [deathau/sliding-panes-obsidian#125]
Obsidian version: 0.16.0 (Insiders Release)
Plugin version: 3.3.0

It appears that the most recent Insider Release (0.16.0) has introduced a new feature -- tabs. They are always on, at least I couldn't find any way to turn this feature off.

With that change, Sliding Panes plugin just doesn't work at all: things that used to be **panes** in one window are now **tabs** or **tab groups**. Regardless of the number of tabs or tab groups, sliding mode behavior just doesn't seem to work anymore, tabs can only be scrolled left and right if their total width exceeds the window width.

I have tested this on Sandbox Vault with a single plugin installed.

**Comment by hschmiedhofer** [comment]
I am curious about what @deathau 's plans are, regarding this fact.

**Comment by approximate** [comment]
Pane Relief plugin has apparently introduced [some kind of sliding pane support ](https://github.com/pjeby/pane-relief#simple-sliding-panes-mode) in the most recent version, but this doesn't seem to work either, or at least I couldn't get it to work.

I suspect tabs will get a bunch of fixes in the upcoming Obsidian updates...

**Comment by kithairon** [comment]
Very much love Sliding Panes – and hope they reappear beside the new tab function. While I like the idea of tabs, I wouldn't want to miss the sliding feature – it has been so great to open a few workspaces with a batch of sliding panes to work on a particular piece of writing. Would appreciate to hear of the developer's plans. Thanks ~

**Comment by deathau** [comment]
I've put out a new minor release that should make sliding panes work again.
They won't be perfect (the idea of the rotated spines has to be completely re-thought due to the fact the title bars are out, and tab bars are in, for example). But panes should slide again, in any case.

**Comment by deathau** [comment]
To provide a little more context, panes are still very much a thing in this new version of obsidian, but when you open a new note in what would've been a new pane previously, it opens in a tab instead. You can drag tabs around to create new panes, and new vertically stacked panes will be sliding with the sliding panes plugin.
Each pane can still contain many tabs. Therefore, at first glance it might seem like sliding panes still isn't doing anything because you're opening tabs and not panes.

**Comment by wowo101** [comment]
@deathau Thanks for this quick fix! As the title bars can be enabled in the "Appearance" settings, maybe there is a way to regain the rotated spines with a little help from the users (i.e. them manually enabling them)?

**Comment by approximate** [comment]
@deathau yep, this seems to work now, thank you very much for the update!

you're right in that panes are still a thing, and i should have called them "panes" instead of "tab groups". the essence of my post was that if you have several panes side-by-side, sliding panes plugin before the update wasn't doing anything at all, whereas after the update there's a combination of settings that kind of works similarly to what is was before tabs were introduced:
- "stacking" should be ON
- "leaf auto-width" should be ON

When those settings aren't ON, sliding panes mode is either no different from normal horizontal scrolling, or the pane sizes just look weird.

you're also right in that title/tab bars and spines will have to be redesigned or re-implemented, but I still suspect there will be some fixes coming from Obsidian devs regarding tabs behavior: there seems to be a number of issues there, including tab bar placement/alignment (might be a theme bug though).

in any case, thanks very much again for the quick fix!

**Comment by benhughes** [comment]
Looks like the plugin has been "sherlocked" and is now native with the new 0.16.2 release.

https://forum.obsidian.md/t/obsidian-release-v0-16-2-insider-build/42829

**Comment by benhughes** [comment]
Want to say congrats that this plugin has been "promoted" to a native feature in 1.0. This has always been my favourite plugin for Obsidian, so thank you for you hard work over the years. Remember copying and pasting it into my CSS file before plugins were a thing.

**Comment by kithairon** [comment]
Tremendous appreciation for SlidingPanes and the work that has gone into it. The concept of sliding panes and the implementation of it in your plugin has changed my way of working – and has been one of the most attractive features of Obsidian. With more than 260k downloads it looks like I#m not the only one. Thanks for your consistent efforts.

**Comment by lkcmgn** [comment]
and the hotkey for "focus on left / right panes doesn't work after the tab features, it bother me a lot, any fix for it ?
