### ISSUE TITLE
Install from Obsidian failed

### ISSUE THREAD

**Issue by mafsi** [deathau/sliding-panes-obsidian#13]
I failed to install v.3.0.2 from inside Obsidian.
I'll do it manually.

**Comment by DutchPete** [comment]
It also failed for me.

**Comment by deathau** [comment]
Ah, my bad. I left an extra 'v' in the manifest that shouldn't be there. Give it a few minutes for the caches to expire then try again (it still doesn't work for me right now, but it should soon).

**Comment by deathau** [comment]
Looks like it's working now. Thanks again for the heads up, guys 👍
