### ISSUE TITLE
Opening a Note in a New Pane Doesn't Select that Pane

### ISSUE THREAD

**Issue by taylorhadden** [deathau/sliding-panes-obsidian#16]
This often results in panes being open so far to the right that they cannot be seen.

**Comment by tallguyjenks** [comment]
➕1️⃣

**Comment by deathau** [comment]
Oh, I see. This is because the newly opened pane isn't active by default 🤔 I'll have to figure out what event gets triggered in this case...

**Comment by deathau** [comment]
I had a chat with Licat, and it turns out there _isn't_ an event for this. However he's considering adding a `layout-changed` event for the future which I can use to catch a newly opened pane and set it as active.

**Comment by pjeby** [comment]
I think the failure to activate the pane should really be considered an Obsidian bug, as it affects Obsidian just as much without this plugin installed.  So I've [reported it to the devs](https://forum.obsidian.md/t/new-pane-does-not-become-active-when-opened-with-link-or-switcher-from-pinned-pane/10298).
