### ISSUE TITLE
Allow auto-scrolling to active pane be toggleable

### ISSUE THREAD

**Issue by manassadasivuni** [deathau/sliding-panes-obsidian#19]
In my workflow, I open and close a lot of notes and the plugin keeps auto-scrolling back to my first (leftmost) note which was quite inconvenient to the extent that I switched back to the CSS-only version. I'm not sure if anyone else has the same issue but being able to disable auto-scrolling would be quite useful

**Comment by deathau** [comment]
The most recently released version has a fix to go to the pane immediately to the left instead of the leftmost note, which will probably help your situation a lot.
