### ISSUE TITLE
Loading workspace issue

### ISSUE THREAD

**Issue by deathau** [deathau/sliding-panes-obsidian#20]
> Found a bug. when I loaded my one of workspaces (workspaces plugin), sliding pane plugin “touched” sidebar.
> ![](https://forum.obsidian.md/uploads/default/e8b2e08e3f469821c61993a593479f0a6a389f13)
https://forum.obsidian.md/t/sliding-panes-andy-matushcak-mode-plugin/7652/36?u=death.au

**Comment by jokysatria** [comment]
I think this bug was gone. I can't reproduce it again. Thanks a lot!

**Comment by deathau** [comment]
Thanks for the info. Looks like I have some checks to do
