### ISSUE TITLE
Error appearing in Console: Uncaught TypeError: Cannot read property 'end' of undefined

### ISSUE THREAD

**Issue by agathauy** [deathau/sliding-panes-obsidian#26]
<img width="415" alt="image" src="https://user-images.githubusercontent.com/17349699/99153019-a6543b80-26e0-11eb-8d2f-af6c03d0ee3e.png">

It doesn't really affect the usage of the thing I think, but still thought I should report this. It's a persistent error that I've been seeing multiple times today. Kudos btw for the plugin! :D

**Comment by deathau** [comment]
Thanks for this, I had another report of this on the Obsidian Discord (it was something to do with autocomplete in the search interface).

What fixed it for them was toggling the plugin off then on again (which makes no sense, but 🤷‍♂️)

I'll keep an eye on this one.

**Comment by deathau** [comment]
I think this was fixed in #22 which I'm putting in the next release.

**Comment by deathau** [comment]
This seems to be fixed as of 3.2.0
Please reopen if it happens again
