### ISSUE TITLE
Can't not open a new window in edit mode use ctrl + click

### ISSUE THREAD

**Issue by OrdinaryYZH** [deathau/sliding-panes-obsidian#27]
ob bersion: 0.9.11
os:windows

edit mode don't worl, but preview mode work :-(

**Comment by deathau** [comment]
I think in edit mode you have to use ctrl+shift+click

**Comment by OrdinaryYZH** [comment]
> I think in edit mode you have to use ctrl+shift+click

It worked, thank you very much!
