### ISSUE TITLE
Feature Request: Auto-resizing of leaves based on available space

### ISSUE THREAD

**Issue by pauljacobson** [deathau/sliding-panes-obsidian#29]
### Summary

This may be related to #12 so apologies for any duplication.

I noticed that the leaves that I open can only be sized using the sizing option in the plugin settings. This can be a little fiddly if I switch between, say, using the tag/local graph sidebar on the right, and just going "full screen" (where both the left and right sidebars are collapsed).

### Steps to reproduce

1. Change the leaves' width to 1000px to better suit my MacBook Pro 15" screen
2. Reload the app to refresh the view (simply changing the width doesn't lead to "correct" rendering)
3. Add new leaves using `Shift` + `Cmd` + `Click` (I think - I still feel like I'm doing this incorrectly)
4. As I add new leaves (aka, open more notes), they eventually take up more of the available space

You can see a rough demo [here](https://d.pr/i/LnP0kY/ZedMq9nGNv):

![](https://d.pr/i/LnP0kY/ZedMq9nGNv+)

_Screenshot direct link:_ https://d.pr/i/LnP0kY/ZedMq9nGNv

### What I'd like to see

Ideally, I'd love to see leaves automatically resize to use the available space in the main note area, taking into account whether I have either the left, right, or both sidebar panes open.

Perhaps an "auto" option in the leave sizing section, like this:

<img width="1349" alt="Markup 2020-11-20 at 18 16 52" src="https://user-images.githubusercontent.com/2912202/99823213-c78fae80-2b5c-11eb-8e86-4d4b837fba29.png">

### What happened instead

Currently, the leave width is set in the plugin settings, and the leaves will only stack more like books on a shelf if there are enough notes open.

As a side issue, I noticed that I need to reload the app for updated leaf sizing to take effect, and for all the notes to be brought into the main note area (I opened a few notes that disappeared off to the right, behind the right panel, and didn't see them until I reloaded the app).

### App / OS version

- macOS 11.0.1
- Obsidian v0.9.15 (installer at v0.9.15)
- Plugin version: v3.1.1

**Comment by deathau** [comment]
An auto-size is something I'd never actually thought of. The general idea of this plugin is to have fixed-width panes, but just having a single pane fill the available space between the spine stacks seems like an obvious addition now that you mention it.

**Comment by deathau** [comment]
This is in 3.2.0 now.
And it seems to be pretty popular! Thanks for the detailed suggestion, @pauljacobson

**Comment by pauljacobson** [comment]
@deathau Thank you for the feedback. I'm glad the feature request was helpful!
