### ISSUE TITLE
Closing a panel sends focus to the leftmost panel in the stack

### ISSUE THREAD

**Issue by taylorhadden** [deathau/sliding-panes-obsidian#3]
This is happening if I close the panel with the keyboard shortcut or with the the x button.

I don't know if this is something that can be accessed by the plugin or if it's just an issue within Obsidian itself.

**Comment by tallguyjenks** [comment]
➕1️⃣ i get the same behavior

**Comment by erichalldev** [comment]
I've actually created a solution to this in my personal plugin. I'll port it over to the sliding panes repo and submit a PR.

**Comment by deathau** [comment]
Thanks for the fix, @erichalldev!
