### ISSUE TITLE
Compatibility Issue: 

### ISSUE THREAD

**Issue by MarioRicalde** [deathau/sliding-panes-obsidian#30]
![image](https://user-images.githubusercontent.com/125900/100001532-eb373c80-2d88-11eb-9360-ac759b4af1f7.png)

Compatibility issue with the following pluigin:
https://github.com/mrjackphil/obsidian-backlinks-in-document

Obsidian Version:
0.9.17

**Comment by deathau** [comment]
Thanks for pointing this one out. It turns out the backlinks pane MrJackphil added counted as a "root" leaf, so I had to be a bit creative in how I identify root leaves

**Comment by MarioRicalde** [comment]
Glad I could help, thank you!
