### ISSUE TITLE
The title has some blur in leaf title.

### ISSUE THREAD

**Issue by skylum1** [deathau/sliding-panes-obsidian#31]
![Inkedbandicam 2020-11-24 12-54-55-003_LI](https://user-images.githubusercontent.com/43382865/100061850-b09ad600-2e54-11eb-84fd-4d379febfc38.jpg)
When I turn on swap rotated header direction this issue is resolved.

**Comment by deathau** [comment]
Whoops. Thanks for the report

**Comment by greenmanspirit** [comment]
As an additional note. This does not show up when the direction of the title is swapped.
