### ISSUE TITLE
Position of search suggestions affected when sliding panes is active

### ISSUE THREAD

**Issue by mgmeyers** [deathau/sliding-panes-obsidian#36]
Hey @deathau! Thanks for this fantastic plugin.

I've been pulling my hair out trying to figure out why the search suggestion box is in the wrong place:

<img width="523" alt="Screen Shot 2020-12-14 at 9 56 23 AM" src="https://user-images.githubusercontent.com/2694747/102117983-eac41b80-3df3-11eb-9f9f-3192ba68e57f.png">

It turns out this only happens when sliding panes are active. Not sure why this is, but I thought I'd let you know!

**Comment by deathau** [comment]
Yeah, sounds like a bug. Probably to do with the fix in positioning autocomplete inside panes also applying to this one when it shouldn't.

Thanks for the report

**Comment by deathau** [comment]
I couldn't figure out how to differentiate between this autocomplete and the ones inside panes. Fortunately, I just removed all the code relating to custom positioning and it seems to work fine, even in panes? I guess something was fixed in Obsidian itself.
