### ISSUE TITLE
Feature Request: Embed note title as horizontal "header" in vertical-title mode

### ISSUE THREAD

**Issue by mambocab** [deathau/sliding-panes-obsidian#45]
I love being able to scroll horizontally through open panes and see all their titles as vertical text. This is true both for those with and without exposed editor windows -- I like being able to see everything I'm editing, e.g. as part of refactoring an evergreen note, including the one I'm currently editing.

However, for the note I'm currently editing, I would like to be able to read the file name as though it were the title of the note. For context, I roughly follow an evergreen notes-style process, so the titles are semantically important. Notably, I do not want to duplicate text across filenames and in-line headers. 

So: my request is that, when I'm using sideways titles, I would like to see the title of notes whose content is visible above their content. I could imagine this looking like an H1 as an example. Notably, it does not need to be editable; I am perfectly happy for it to be read-only.

I am happy to take a crack at this and submit a PR (or implement it for myself) if you don't anticipate hopping on this anytime soon; would appreciate a pointer in the right direction if that's the case.

-------

(Adding below the fold to avoid muddying the request -- thanks so much for all your efforts and for sharing your tools. I've benefitted immensely.)

**Comment by deathau** [comment]
This is something I have actually had rattling around in the back of my head for a long time, but I hadn't considered making it part of this plugin, thinking instead to perhaps make it a plugin of its own.

I'd done some stuff to style the title in my Notation theme to make the title look like it was a header in the document (like Notion does) but that's developed issues I haven't been able to work around, and always caused some dodgyness with linked panes not scrolling together.

All of this is to say: I'd love for you to take a crack at it, but I do think it would be better in its own plugin than a part of this one, even though it is complementary functionality. What are your thoughts on this?

**Comment by deathau** [comment]
Additionally, my _eventual_ plan was to eventually introduce an _extra_ horizontal "spine" that only appears when the pane is scrolled out of view (how scrolling panes works in publish, see <https://publish.obsidian.md/death-au>), leaving the title bar in place at the top.

**Comment by mambocab** [comment]
> … I hadn't considered making it part of this plugin, thinking instead to perhaps make it a plugin of its own… I do think it would be better in its own plugin than a part of this one, even though it is complementary functionality. What are your thoughts on this?

Ah, this is worth discussing -- I think I've over-articulated one solution at the expense of describing my problem.

Obsidian's default behavior, and the behavior of this plugin with horizontal titlebars, meet my need in the case of notes whose edit window is visible. The missing feature reduces to "let me read the title of this note above its body". I was over-prescriptive/latching on to the wrong thing in mentioning "looks like an H1" in my request.

Since Obsidian "natively" meets the "let me read the title horizontally" need, but sideways-titlebar-mode does not, I'd framed this as a request for the sideways-titlebar mode for the plugin. Does that make sense?

> … introduce an extra horizontal "spine" that only appears when the pane is scrolled out of view (how scrolling panes works in publish, see https://publish.obsidian.md/death-au), leaving the title bar in place at the top.

This implementation would hit the need exactly. I've attached a screenshot below to make sure we're talking about the same thing.

So to rephrase with my new clarity around this:

- I want to see all the filenames of my open-but-not-centered-for-editing notes. Vertical is fine.
- I want to see the filenames of my centered-for-editing notes close to the note and highly readable/skimmable. In practical terms that means "horizontally, and above the editable areas of those notes".

Thanks for engaging on this!

-------

Screenshot of Obsidian Publish showing visible notes' titles as "headers" above their text, and showing the titles of notes scrolled offscreen horizontally as vertical bars.

It's worth noting that I'd be perfectly happy with a view of notes that included vertical titlebars for visible notes. It's redundant and "wastes" a little space but that's fine by me. I'd actually slightly prefer it -- see the `Instant Gratification Monkey` note, whose title is not shown in its entirety.

![8BB81EE4-B0E5-4628-80C9-9EB1BB50BE24](https://user-images.githubusercontent.com/3753769/104474863-72847d80-558c-11eb-831a-2b2920c917db.jpeg)

**Comment by mgmeyers** [comment]
@deathau FYI, I do this in the California Coast theme using a somewhat hacky approach: https://github.com/mgmeyers/obsidian-california-coast-settings/blob/main/extensions/embeddedHeadings.ts

<img width="583" alt="Screen Shot 2021-01-29 at 1 21 56 PM" src="https://user-images.githubusercontent.com/2694747/106328665-0d3fb600-6235-11eb-9d67-85d1fbe8c492.png">


<img width="917" alt="Screen Shot 2021-01-29 at 1 18 42 PM" src="https://user-images.githubusercontent.com/2694747/106328455-b76b0e00-6234-11eb-96f5-f8f9d053d6e8.png">

**Comment by jacklaing** [comment]
@mgmeyers This is great, I don't use California Coast but installed your settings plugin just so I could turn this feature on. I definitely recommend packaging this as a standalone plugin if it's not too much hassle for you, or letting @deathau fork and merge it into the Sliding Panes settings.

Is it possible to make the title inherit the pane title header that has been set by the active theme/snippet?

**Comment by mgmeyers** [comment]
@jacklaing Yeah, I could probably pull it out into it's own plugin. I'd also recommend checking out this plugin as an alternative: https://forum.obsidian.md/t/plugin-for-keeping-the-filename-and-first-heading-of-a-file-in-sync/12042

**Comment by jacklaing** [comment]
Thanks for the tip, but I think that's not quite right for me since it would create duplicate headers in Publish.

**Comment by mambocab** [comment]
I will note -- using CA Coast with the "filenames-as-heading" option set has met my needs here. I think there's value in the behavior as a feature of Andy's Mode still but given the pairing as it stands, I'm good to go.

**Comment by dltj** [comment]
> @deathau FYI, I do this in the California Coast theme using a somewhat hacky approach: https://github.com/mgmeyers/obsidian-california-coast-settings/blob/main/extensions/embeddedHeadings.ts
> 
> <img alt="Screen Shot 2021-01-29 at 1 21 56 PM" width="583" src="https://user-images.githubusercontent.com/2694747/106328665-0d3fb600-6235-11eb-9d67-85d1fbe8c492.png">

@mgmeyers : I've installed the _California Coast_ theme and the _Style Settings_ plugin, but I don't see an option for "Display note file names as headings" in the Style Settings plugin options — what am I missing?

**Comment by mgmeyers** [comment]
@dltj Ah, this has been moved into its own plugin: https://github.com/mgmeyers/obsidian-embedded-note-titles

**Comment by dltj** [comment]
@mgmeyers Oh, perfect...thank you for pulling that out (although I'm already enjoying the California Coast theme and will probably keep that as well).

**Comment by mambocab** [comment]
The new plugin meets my need and so I'm comfortable closing this issue. Thanks all for your comments and for your work on these plugins!
