### ISSUE TITLE
sliding pane or split vertically? 

### ISSUE THREAD

**Issue by purpleweed** [deathau/sliding-panes-obsidian#63]
sliding panes arent working for me, note pages doesnt open as depicted , instead it opens just like switching notes, sliding panes is working only when i make multiple split pages. 
and i have reinstalled the plug-ins like many times 

https://user-images.githubusercontent.com/85365408/120846346-9c682c00-c58f-11eb-8fb6-21e868da71bb.mp4

**Comment by deathau** [comment]
That's how the plugin works currently.

Sliding Panes helps you manage multiple open panes, it doesn't actually create those panes for you. You can also [ctrl or cmd]+click on a link to open it in a new pane.
