### ISSUE TITLE
FYI, not working at all

### ISSUE THREAD

**Issue by dixonge** [deathau/sliding-panes-obsidian#72]
In preview mode (or editing mode) clicking a link to another local file just opens the new file. The old file completely disappears. Nothing 'slides' anywhere...

MacOS 11.3 (Big Sur)
Obsidian 0.12.19 (latest)
Sliding Panes v3.2.3 (latest)

**Comment by ipedrazas** [comment]
Have you tried doing CMD+Shift when clicking on the link?

**Comment by dixonge** [comment]
Why? I have seen nothing in any documentation for this plugin that indicates that extra keys are required for the sliding panels to work...

**Comment by deathau** [comment]
The sliding panes work as an alternate way to view multiple open panes. In Obsidian, you can open new panes by cmd/ctrl+shift+clicking on a link in edit mode, or cmd/ctrl+clicking on a link in preview. There are also options in many menus to open things in new panes.
This plugin doesn't touch any of that functionality. It just takes multiple panes from splitting the screen to sliding instead.

**Comment by dixonge** [comment]
as I mentioned in my original issue, nothing slid. There was no sliding. There were no multiple panes. Just a new open document with no remaining link or spline for the original document. True for both edit and preview modes.

**Comment by deathau** [comment]
"Multiple panes" are a core feature of Obsidian. You must open new panes yourself by cmd+clicking on links, files in the file explorer, etc. Clicking a link to open a file will open it in the same pane, just as in core Obsidian. That feature has not been changed.

**Comment by dixonge** [comment]
It appears I had a fundamental misunderstanding of both the core and plugin features. I'm looking for something more like Andy's blog, which would be more like plain clicking in preview mode and partial sliding. My apologies.

**Comment by deathau** [comment]
No worries. I see what you mean, and I can definitely see why that would be useful. I may consider adding an option to auto-open-in-new-pane in future (if that's somethjng I can even work out how to achieve)
