### ISSUE TITLE
Autocomplete dropdown when linking to another entry is offset if you are not editing the leftmost pane

### ISSUE THREAD

**Issue by deathau** [deathau/sliding-panes-obsidian#9]

**Comment by erichalldev** [comment]
I've looked into solving this and it'll be tricky with the current API version (0.9.11). As far as I know there's no way to access the suggestion-container (the autocomplete dropdown) from the API. I think an event could be added to listen for the suggestion-container being added to the DOM and then we could change the coordinates of the DOM element itself. Then there's the issue of determining the coordinates but that might not be as hard. I think the cursor position can be retrieved using the cmEditor of the view, and then I think an offset will need to calculated based on the leaf's position.

**Comment by erichalldev** [comment]
This was way easier than I thought it would be. I'll be submitting a PR for it shortly.

**Comment by erichalldev** [comment]
I spoke too soon. I'm still working out a small kink.

**Comment by deathau** [comment]
Thanks a lot for tackling this one @erichalldev 👍
